import type { Metadata } from "next";
import "./globals.css";
type Props = {
  children: React.ReactNode;
  modal: React.ReactNode;
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang="en">
      <body>
        {children}
        {modal}
      </body>
    </html>
  );
}
